name: Build and Push Docker Image to GHCR

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # Checkout 仓库代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Docker 登录
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}  # 使用 TOKEN 进行身份验证

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/60s:${{ github.event.inputs.tag }} .

      # 推送 Docker 镜像到 GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/60s:${{ github.event.inputs.tag }}
